### ISSUE TITLE
Export to PDF formatting issues

### ISSUE THREAD

**Issue by valinortech** [sergey900553/obsidian_githublike_theme#2]
When using the native Export to PDF feature in Obsidian, bolded text appears blank and the first indented bullet point overlaps the one above it. This doesn't appear to happen with other themes I've tested. 

![Screenshot 2022-07-18 085636](https://user-images.githubusercontent.com/43941723/179516339-422cda0b-9c6e-4867-985b-c754348f9694.png)

**Comment by sergey900553** [comment]
Fixed. Previously, the list was displayed a little crookedly in obsidian. Apparently they fixed it and now my "fix" has become a bug. Reinstall theme (not update)

**Comment by valinortech** [comment]
Working great now. Thank you!

**Comment by ruperlopez** [comment]
I reinstalled the theme but the problem persists, bold text when I export as a pdf is white and it can't be seen.
